name: torch-levenberg-marquardt-cuda

channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python=3.10.11
  - cudatoolkit=11.8
  - numpy
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-lightning=1.9.3
  - tqdm
  - torchmetrics
  - torchvision
  - bokeh
  - ipykernel
  - black
  - flake8
  - pip:
      - -e .
